// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTodo(arg1) {
  return window['go']['main']['TodoApp']['AddTodo'](arg1);
}

export function DeleteTodo(arg1) {
  return window['go']['main']['TodoApp']['DeleteTodo'](arg1);
}

export function GetTodos() {
  return window['go']['main']['TodoApp']['GetTodos']();
}

export function ToggleTodo(arg1) {
  return window['go']['main']['TodoApp']['ToggleTodo'](arg1);
}
